name: Build demos
on:
  push:
    branches-ignore:
      - data
      - gh-pages
    tags:
      - '**'
  pull_request:
    branches-ignore:
      - data
      - gh-pages
  workflow_dispatch:

jobs:
  # Generate matrix job. Detects changed files and runs only relevant builds
  generate-matrix:
    name: Generate matrix for build
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: 1
    outputs:
      matrix-android: ${{ steps.set-matrix.outputs.matrix-android }}
      empty-matrix-android: ${{ steps.set-matrix.outputs.empty-matrix-android }}
    steps:
      - uses: actions/checkout@v2
      - name: Check changed files
        id: diff
        run: |
          # See https://github.community/t/check-pushed-file-changes-with-git-diff-tree-in-github-actions/17220/10
          if [ $GITHUB_BASE_REF ]; then
            # Pull Request
            git fetch origin $GITHUB_BASE_REF --depth=1
            export DIFF=$( git diff --name-only origin/$GITHUB_BASE_REF $GITHUB_SHA )
            echo "Diff between origin/$GITHUB_BASE_REF and $GITHUB_SHA"
          else
            # Push
            git fetch origin ${{ github.event.before }} --depth=1
            export DIFF=$( git diff --name-only ${{ github.event.before }} $GITHUB_SHA )
            echo "Diff between ${{ github.event.before }} and $GITHUB_SHA"
          fi
          echo "$DIFF"
          # Escape newlines (replace \n with %0A)
          echo "::set-output name=diff::$( echo "$DIFF" | sed ':a;N;$!ba;s/\n/%0A/g' )"
      - name: Set matrix for build
        id: set-matrix
        run: |
          echo "${{ steps.diff.outputs.diff }}"
          python3 .ci/generate_matrix.py "${{ steps.diff.outputs.diff }}"

  # Build job. Builds every demo app for Android with Buildozer
  build-android:
    name: Build Android [${{ matrix.demo-name }}]
    needs: generate-matrix
    if: ${{ needs.generate-matrix.outputs.empty-matrix-android == 'false' }}
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix-android)}}
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: master

    - name: Set numeric version
      id: settings
      run: echo "::set-output name=numeric_version::$(date +%Y%m%d%H%M%S)"

    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        repository_root: master
        workdir: demos/${{ matrix.demo-name }}
      env:
        BUILDOZER_APP_ANDROID_NUMERIC_VERSION: ${{ steps.settings.outputs.numeric_version }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: package ${{ matrix.demo-name }}
        path: ${{ steps.buildozer.outputs.filename }}

    - name: Checkout kivymd/storage repository (binaries branch)
      uses: actions/checkout@v2
      if: github.event_name == 'push'
      with:
        path: binaries
        repository: kivymd/storage
        ref: binaries # Branch name
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v2
      if: github.event_name == 'push'
      with:
        python-version: 3.7
        architecture: x64

    - name: Push binary to kivymd/storage repository (binaries branch)
      if: github.event_name == 'push'
      run: |
        # Use personal token to push (when using GITHUB_TOKEN, it will not allow pushes from PR)
        cd binaries && \
          git config user.name "KivyMD Bot" && \
          git config user.email 69076719+KivyMD-Bot@users.noreply.github.com && \
          git remote set-url origin https://KivyMD-Bot:${{ secrets.GH_PAT }}@github.com/kivymd/storage && \
          cd ..
        python master/.ci/move_binary.py "${{ steps.buildozer.outputs.filename }}" master binaries "demo_${{ matrix.demo-name }}"
